# Configuraton File #
#===================#
title: Jekyll Arabica Boilerplate
email: sricharan.krishnan@gmail.com
github_username: sricharankrishnan (https://github.com/sricharankrishnan/)

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Expect the following details to be excluded during the final build process
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - package.json
   - package-lock.json

# Handling Permalinks.
permalink: /:categories/:title/

sass:
  style: compressed

# Default Front Matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      title: "Jekyll Arabica Boilerplate | Free Github Download"
      metaDescription: "A really simple project that serves as a boilerplate for developers building front end websites with Jekyll."
      metaKeywords: "jekyll, jekyll boilerplate, jekyll boilerplate template, jekyll development environment, jekyll arabica boilerplate, jekyll lava, jekyll website builder, jekyll website examples, jekyll project, jekyll environment how to"

